name: publish grocy container images

on:
  release:
    types: [published]

jobs:
  build_and_push_latest:
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # permit upload of sarif output from the workflow
    env:
      GROCY_IMAGE_TAG: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v3
    # Enable Ubuntu (jammy) repository packages, to ensure that a recent version of 'buildah' is available
    - run: echo "deb http://archive.ubuntu.com/ubuntu/ jammy main universe" | sudo tee -a /etc/apt/sources.list
    - run: echo "deb http://archive.ubuntu.com/ubuntu/ jammy-security main universe" | sudo tee -a /etc/apt/sources.list
    - run: sudo apt-get update
    - run: sudo apt-get install -y buildah qemu-user-static
    # Determine the grocy application version to bundle based on the image tag to publish
    - run: echo "GROCY_VERSION=${{ env.GROCY_IMAGE_TAG }}" | sed -e "s/-[0-9a-z]*$//" >> $GITHUB_ENV
    # Build multi-architecture container manifests
    - id: build-grocy-backend
      uses: redhat-actions/buildah-build@v2.12
      with:
        image: grocy-backend
        tags: ${{ env.GROCY_IMAGE_TAG }} ${{ env.GROCY_VERSION }}
        platforms: linux/amd64, linux/arm64/v8
        containerfiles: Containerfile-backend
        build-args: |
          GROCY_VERSION=${{ env.GROCY_VERSION }}
        labels: |
          org.opencontainers.image.documentation=https://grocy.info/
          org.opencontainers.image.source=https://github.com/grocy/grocy-docker/
          org.opencontainers.image.version=${{ env.GROCY_IMAGE_TAG }}
          org.opencontainers.image.licenses=MIT
    - id: build-grocy-frontend
      uses: redhat-actions/buildah-build@v2.12
      with:
        image: grocy-frontend
        tags: ${{ env.GROCY_IMAGE_TAG }} ${{ env.GROCY_VERSION }}
        platforms: linux/amd64, linux/arm64/v8
        containerfiles: Containerfile-frontend
        build-args: |
          GROCY_VERSION=${{ env.GROCY_VERSION }}
        labels: |
          org.opencontainers.image.documentation=https://grocy.info/
          org.opencontainers.image.source=https://github.com/grocy/grocy-docker/
          org.opencontainers.image.version=${{ env.GROCY_IMAGE_TAG }}
          org.opencontainers.image.licenses=MIT
    # Publish the container manifests
    - uses: redhat-actions/push-to-registry@v2.7
      with:
        image: ${{ steps.build-grocy-backend.outputs.image }}
        tags: ${{ steps.build-grocy-backend.outputs.tags }}
        registry: docker.io/towo
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: redhat-actions/push-to-registry@v2.7
      with:
        image: ${{ steps.build-grocy-frontend.outputs.image }}
        tags: ${{ steps.build-grocy-frontend.outputs.tags }}
        registry: docker.io/towo
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
